# Generated by Django 4.2.2 on 2023-07-27 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partstr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', partstr.models.PartNumber(max_length=20, unique=True)),
                ('designation', partstr.models.Designation(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mass', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('xcg', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('ycg', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('zcg', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partstr.level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='partstr.part')),
                ('pntype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partstr.pntype')),
                ('resp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partstr.status')),
            ],
            options={
                'ordering': ['partnumber'],
                'indexes': [models.Index(fields=['partnumber'], name='partstr_par_partnum_8f266c_idx')],
            },
        ),
    ]
