# Generated by Django 4.2.2 on 2023-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partstr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleasedManager',
        ),
        migrations.AddField(
            model_name='part',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='catia_data/'),
        ),
    ]
