# Generated by Django 4.2.2 on 2023-06-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partstr', '0003_alter_part_level_alter_part_resp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pntype',
            old_name='pntype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
    ]
